# configuration ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈

relay:
  verbose:         False
  # topology configuration for the ESP32-NOW relay chain.
  # the order of this list strictly defines the relay path (Node 1 -> Node N).
  devices:
    - name:        "Node 1 - TinyS3 w antenna"
      mac:         "dc:54:75:eb:69:c8"
      enabled:      True
#   - name:        "Node 2 - TinyPICO green"
#     mac:         "64:b7:08:90:5c:c4"
#     enabled:      True
    - name:        "Node 2 - Waveshare ESP32-S3 Zero"
      mac:         "50:78:7d:17:fe:d8"
      enabled:      True
    - name:        "Node 3 - TinyPICO light green"
      mac:         "24:a1:60:75:ba:84"
      enabled:      True
    - name:        "Node 4 - TinyPICO red"
      mac:         "98:cd:ac:d3:41:b8"
      enabled:      True
    - name:        "Node 5 - FeatherS2"
      mac:         "7c:df:a1:03:4d:fe"
      enabled:      True

initiator:
  pin:             5

